#!/usr/bin/env python3
"""
Generate an HTML report with embedded flowcharts
"""

import sys
import base64
from pathlib import Path
from datetime import datetime

def generate_html_report(flowcharts_dir: str = "flowcharts", output_file: str = "flowcharts_report.html"):
    """Generate HTML report with embedded images"""
    
    flowcharts_path = Path(flowcharts_dir)
    if not flowcharts_path.exists():
        print(f"Error: {flowcharts_dir} directory not found")
        return
    
    # Find all PNG files
    images = list(flowcharts_path.glob("*.png"))
    
    if not images:
        print(f"No PNG files found in {flowcharts_dir}")
        return
    
    # Generate HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>C++ Project Flowcharts</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        h1 {{
            color: #333;
            text-align: center;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 10px;
        }}
        .flowchart {{
            background: white;
            margin: 30px 0;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .flowchart h2 {{
            color: #4CAF50;
            margin-top: 0;
        }}
        .flowchart img {{
            max-width: 100%;
            height: auto;
            border: 1px solid #ddd;
            border-radius: 4px;
            display: block;
            margin: 20px auto;
        }}
        .metadata {{
            color: #666;
            font-size: 14px;
            margin-top: 10px;
        }}
        .footer {{
            text-align: center;
            margin-top: 50px;
            padding: 20px;
            color: #666;
            border-top: 1px solid #ddd;
        }}
        .download-btn {{
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 4px;
            display: inline-block;
            margin: 10px 5px;
        }}
        .download-btn:hover {{
            background-color: #45a049;
        }}
    </style>
</head>
<body>
    <h1>🔍 C++ Project Analysis - Flowcharts</h1>
    <p style="text-align: center; color: #666;">Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
    
"""
    
    # Add each flowchart
    for img_path in sorted(images):
        # Read and encode image
        with open(img_path, 'rb') as f:
            img_data = base64.b64encode(f.read()).decode('utf-8')
        
        # Generate title from filename
        title = img_path.stem.replace('_', ' ').title()
        
        html += f"""
    <div class="flowchart">
        <h2>📊 {title}</h2>
        <img src="data:image/png;base64,{img_data}" alt="{title}">
        <div class="metadata">
            <strong>File:</strong> {img_path.name}<br>
            <strong>Size:</strong> {img_path.stat().st_size / 1024:.2f} KB
        </div>
    </div>
"""
    
    html += """
    <div class="footer">
        <p>Generated by C++ Analysis Agent</p>
        <p>Powered by LangChain + Ollama + ChromaDB</p>
    </div>
</body>
</html>
"""
    
    # Write HTML file
    output_path = Path(output_file)
    output_path.write_text(html, encoding='utf-8')
    
    print(f"✓ HTML report generated: {output_path.absolute()}")
    print(f"✓ Embedded {len(images)} flowcharts")
    print(f"\nTo view:")
    print(f"  1. Download: scp user@server:{output_path.absolute()} .")
    print(f"  2. Open in browser: {output_path.name}")


if __name__ == '__main__':
    if len(sys.argv) > 1:
        flowcharts_dir = sys.argv[1]
    else:
        flowcharts_dir = "flowcharts"
    
    if len(sys.argv) > 2:
        output_file = sys.argv[2]
    else:
        output_file = "flowcharts_report.html"
    
    generate_html_report(flowcharts_dir, output_file)

